# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0 WITH LLVM-exception

import argparse
import itertools
import multiprocessing
import subprocess
import sys
import warnings

from collections.abc import Iterable
from dataclasses import astuple, replace
from enum import Enum
from pathlib import Path
from typing import Any, TypeVar, cast

from mako.lookup import TemplateLookup

from .config import get_config
from .gen_lookup import (
    Lookup,
    datatype,
    direction,
    dist_types,
    inout_mods,
    order_kind,
    twiddleness,
)
from .targets import (
    ASIMDHP_TARGET,
    KERNEL_TARGETS,
    NEON_TARGET,
    SME_TARGET,
    SVE_TARGET,
    KernelTarget,
)

T = TypeVar("T")
E = TypeVar("E", bound=Enum)

TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"
TEMPLATES = TemplateLookup(directories=[TEMPLATES_DIR])
TYPE_TRIPLES: list[str] = [
    "ppp",
    "jjj",
    "ccc",
    "zzz",
    "ppr",
    "jjh",
    "ccs",
    "zzd",
    "rpp",
    "hjj",
    "scc",
    "dzz",
]
FBITS_MAP: dict[str, int | None] = {"q7": 7, "q15": 15, "none": None}


def run(cmd: list[str]) -> str:
    p = subprocess.run(
        [str(x) for x in cmd], check=True, capture_output=True, text=True
    )
    return p.stdout


def gen_one_asm(
    exe: Path,
    order: order_kind,
    n: int | None,
    fbits: int | None,
    tx: datatype,
    tw: datatype,
    ty: datatype,
    twid: twiddleness,
    dir: direction | None,
    mod: inout_mods | None,
    dist: dist_types,
    target: KernelTarget,
) -> str:
    """generate single kernel using gen_asm executable"""
    cmd = [
        str(exe),
        target.name,
        "-" if order == order_kind.na else str(order),
        str(n),
        "-" if fbits is None else f"q{fbits}",
        f"{tx}{tw}{ty}",
        twid.value,
        str(dir),
        str(mod or "-"),
        str(dist),
    ]
    try:
        text = run(cmd)
    except subprocess.CalledProcessError as e:
        print(f"Failed command: {' '.join(cmd)}")
        raise e

    return text


def gen_all_asm(exe: Path, target: KernelTarget, lookup: Lookup) -> list[str]:
    """gather kernels produced by gen_asm executable"""
    order, ns, fbits, tx, tw, ty, twid, dirs, mod, dist, _ = astuple(lookup)

    with multiprocessing.Pool() as pool:
        return pool.starmap(
            gen_one_asm,
            [
                (exe, order, n, fbits, tx, tw, ty, twid, dir, mod, dist, target)
                for n, dir in itertools.product(ns, dirs)
            ],
        )


def gen_asm(
    exe: Path,
    config: list[Lookup],
    outdir: Path,
    write: bool,
    excluded_files: set[Path],
) -> bool:
    """
    Returns True if write is True and at least one of the generated .S
    files has changed, otherwise returns False.

    If write is True, .S files are (over-)written with kernels generated by
    gen_asm executable.
    """
    outdir.mkdir(parents=True, exist_ok=True)

    # Get list of files, remove any we wouldn't write at the end.
    files_to_rm = set(outdir.rglob("*.S"))
    if excluded_files:
        for excluded in excluded_files:
            files_to_rm.discard(outdir / excluded)

    num_changed = 0
    num_unchanged = 0
    for lookup in config:
        for target in lookup.targets:
            outfile = outdir / target.name / lookup.src
            files_to_rm.discard(outfile)

            kernels = gen_all_asm(exe, target, lookup)
            template = TEMPLATES.get_template("kernels.S.mako")
            text = template.render(lookup=lookup, kernels=kernels)

            existing_text = outfile.read_text() if outfile.exists() else ""
            if text == existing_text:
                num_unchanged += 1
                print(f"-- File is unchanged: {outfile}")
                continue

            num_changed += 1
            if write:
                outfile.parent.mkdir(parents=True, exist_ok=True)
                outfile.write_text(text)
                print(f"-- Kernels written to: {outfile}")
            else:
                print(f"-- File would be changed: {outfile}")

    if write:
        for path in files_to_rm:
            path.unlink()

    print("-- Done:")
    print(f"-- Regenerated files: {num_changed}")
    print(f"-- Unchanged files: {num_unchanged} ")
    print(f"-- Removed files: {len(files_to_rm)}")

    return num_changed > 0 or len(files_to_rm) > 0


def _match(value: T, allowed: set[T] | None) -> bool:
    return allowed is None or value in allowed


def _filter_config(
    config: list[Lookup],
    *,
    orders: set[order_kind] | None,
    fbits: set[int | None] | None,
    types: set[str] | None,
    twids: set[twiddleness] | None,
    mods: set[inout_mods | None] | None,
    dists: set[dist_types] | None,
    targets: set[KernelTarget] | None,
) -> tuple[list[Lookup], set[Path]]:
    filtered: list[Lookup] = []
    excluded_files: set[Path] = set()

    def exclude_lookup(
        lookup: Lookup, targets: list[KernelTarget] | None = None
    ) -> None:
        for target in targets or lookup.targets:
            excluded_files.add(Path(target.name) / lookup.src)

    for lookup in config:
        if not _match(lookup.order, orders):
            exclude_lookup(lookup)
            continue
        if not _match(lookup.fbits, fbits):
            exclude_lookup(lookup)
            continue
        if not _match(f"{lookup.tx}{lookup.tw}{lookup.ty}", types):
            exclude_lookup(lookup)
            continue
        if not _match(lookup.twid, twids):
            exclude_lookup(lookup)
            continue
        if not _match(lookup.mod, mods):
            exclude_lookup(lookup)
            continue
        if not _match(lookup.dist, dists):
            exclude_lookup(lookup)
            continue

        lookup_targets: list[KernelTarget] = lookup.targets
        if targets is not None:
            lookup_targets = [target for target in lookup.targets if target in targets]
            excluded_targets = [
                target for target in lookup.targets if target not in targets
            ]
            if excluded_targets:
                exclude_lookup(lookup, excluded_targets)
            if not lookup_targets:
                continue

        filtered.append(replace(lookup, targets=lookup_targets))

    return filtered, excluded_files


def render_template(
    template_filename: str,
    output_path: Path,
    context: dict[str, Any],
    write: bool,
    clang_format: bool = True,
) -> bool:
    """Render template and optionally clang-format output"""
    template = TEMPLATES.get_template(template_filename)
    text = cast(str, template.render(**context))
    if clang_format:
        text = subprocess.run(
            ["clang-format", f"--assume-filename={output_path}"],
            input=text,
            text=True,
            capture_output=True,
            check=True,
        ).stdout

    # Read existing file to validate whether we are introducing changes
    existing_text = output_path.read_text() if output_path.exists() else ""

    has_changed = text != existing_text
    if has_changed:
        if write:
            print(f"{output_path} updated")
            output_path.write_text(text)
        else:
            print(f"{output_path} would be changed")
    return has_changed


def render(config: list[Lookup], ns: list[int], outdir: Path, write: bool) -> bool:
    header_name = "kernels.hpp"
    context = {
        "config": config,
        "kernel_targets": KERNEL_TARGETS,
        "neon": NEON_TARGET,
        "asimdhp": ASIMDHP_TARGET,
        "sve": SVE_TARGET,
        "sme": SME_TARGET,
        "kernel_header_name": header_name,
        "table_size": max(ns) + 1,
        "uun": dist_types.uun,
    }

    return any(
        (
            render_template("kernels.hpp.mako", outdir / header_name, context, write),
            render_template(
                "kernel_lookup.hpp.mako", outdir / "kernel_lookup.hpp", context, write
            ),
            render_template(
                "aot_kernel_lookup.cpp.mako",
                outdir / "aot_kernel_lookup.cpp",
                context,
                write,
            ),
            render_template(
                "kernels.cmake.mako",
                outdir / "kernels.cmake",
                context,
                write,
                clang_format=False,
            ),
        )
    )


def main() -> int:
    target_names = {target.name: target for target in KERNEL_TARGETS}
    parser = argparse.ArgumentParser(
        description="generate FFT kernels and lookup functions"
    )
    parser.add_argument("exe", type=Path, help="Path to gen_asm executable")
    default_outdir = Path(__file__).resolve().parents[2] / "src" / "providers" / "aot"
    parser.add_argument(
        "outdir",
        nargs="?",
        type=Path,
        default=default_outdir,
        help="Path to output directory",
    )
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Return 1 if kernels have changed, otherwise return 0. No files are changed",
    )
    parser.add_argument(
        "--target",
        "--arch",
        dest="target",
        action="extend",
        nargs="+",
        help="Filter kernel targets",
        choices=target_names,
    )
    parser.add_argument(
        "--order",
        action="extend",
        nargs="+",
        help="Filter orders",
        choices=[item.name for item in order_kind],
    )
    parser.add_argument(
        "--fbits",
        action="extend",
        nargs="+",
        help="Filter fixed-point bits",
        choices=FBITS_MAP.keys(),
    )
    parser.add_argument(
        "--types",
        action="extend",
        nargs="+",
        help="Filter type triples",
        choices=TYPE_TRIPLES,
    )
    parser.add_argument(
        "--twid",
        action="extend",
        nargs="+",
        help="Filter twiddleness",
        choices=[item.name for item in twiddleness],
    )
    parser.add_argument(
        "--mod",
        action="extend",
        nargs="+",
        help="Filter modifiers",
        choices=[item.name for item in inout_mods] + ["none"],
    )
    parser.add_argument(
        "--dist",
        action="extend",
        nargs="+",
        help="Filter distributions",
        choices=[item.name for item in dist_types],
    )

    args = parser.parse_args()
    exe: Path = args.exe
    outdir: Path = args.outdir
    check_only: bool = args.check_only

    ns = list(range(2, 20 + 1))
    config: list[Lookup] = get_config(ns)

    def enum_map(enum_cls: Iterable[E]) -> dict[str, E]:
        return {item.name: item for item in enum_cls}

    def resolve_values(
        values: list[str] | None,
        enum_cls: Iterable[E],
        *,
        allow_none: bool = False,
        extra: dict[str, E] | None = None,
    ) -> set[E | None] | None:
        if not values:
            return None
        mapping = enum_map(enum_cls)
        if extra:
            mapping.update(extra)
        resolved: set[E | None] = set()
        for value in values:
            if allow_none and value == "none":
                resolved.add(None)
                continue
            resolved.add(mapping[value])
        return resolved

    # Resolve CLI strings into enum values for filtering.
    targets = {target_names[name] for name in args.target} if args.target else None
    orders = cast(set[order_kind] | None, resolve_values(args.order, order_kind))
    twids = cast(
        set[twiddleness] | None,
        resolve_values(
            args.twid, twiddleness, extra={twid.value: twid for twid in twiddleness}
        ),
    )
    mods = cast(
        set[inout_mods | None] | None,
        resolve_values(args.mod, inout_mods, allow_none=True),
    )
    dists = cast(set[dist_types] | None, resolve_values(args.dist, dist_types))
    fbits = {FBITS_MAP[value] for value in args.fbits} if args.fbits else None

    filtered_config, excluded_files = _filter_config(
        config,
        orders=orders,
        fbits=fbits,
        types=args.types,
        twids=twids,
        mods=mods,
        dists=dists,
        targets=targets,
    )

    has_changed = gen_asm(
        exe,
        filtered_config,
        outdir / "asm",
        not check_only,
        excluded_files,
    )

    if excluded_files:
        warnings.warn(
            "Skipping lookup table regeneration because filters were applied. "
            "Run without filters to regenerate metadata if kernel sets change.",
            stacklevel=2,
        )
    else:
        metadata_changed = render(config, ns, outdir, not check_only)
        has_changed = has_changed or metadata_changed

    if check_only:
        return int(has_changed)
    else:
        return 0


if __name__ == "__main__":
    sys.exit(main())
