find_package(Python3 REQUIRED COMPONENTS Interpreter)

function(sloejit_test TEST_NAME)
  list(APPEND SLOEJIT_TEST_FILES "${CMAKE_CURRENT_SOURCE_DIR}/${TEST_NAME}.cpp")
  set(SLOEJIT_TEST_FILES
      "${SLOEJIT_TEST_FILES}"
      PARENT_SCOPE)

  add_executable(sloejit_${TEST_NAME} ${TEST_NAME}.cpp)
  target_link_libraries(sloejit_${TEST_NAME} PRIVATE sloejit)
  add_test(NAME sloejit_${TEST_NAME} COMMAND sloejit_${TEST_NAME})
endfunction()

sloejit_test(regset)
sloejit_test(bl_example)
sloejit_test(fft2_example)
sloejit_test(long_aarch64)
sloejit_test(plfft_ab_32)

# Keep this sorted.
sloejit_test(add)
sloejit_test(adds)
sloejit_test(addsvl)
sloejit_test(addvl)
sloejit_test(adr)
sloejit_test(adrp)
sloejit_test(and)
sloejit_test(asr)
sloejit_test(b_eq)
sloejit_test(b_ge)
sloejit_test(b_gt)
sloejit_test(b_le)
sloejit_test(b_lt)
sloejit_test(b_ne)
sloejit_test(cntb)
sloejit_test(cntd)
sloejit_test(cnth)
sloejit_test(cntp)
sloejit_test(cntw)
sloejit_test(csel)
sloejit_test(dup)
sloejit_test(ext)
sloejit_test(fadd)
sloejit_test(fcmla)
sloejit_test(fcvt)
sloejit_test(fcvtl)
sloejit_test(fcvtn)
sloejit_test(fmla)
sloejit_test(fmls)
sloejit_test(fmov)
sloejit_test(fmul)
sloejit_test(fneg)
sloejit_test(fsub)
sloejit_test(incb)
sloejit_test(incd)
sloejit_test(inch)
sloejit_test(incw)
sloejit_test(index)
sloejit_test(ld1b)
sloejit_test(ld1d)
sloejit_test(ld1h)
sloejit_test(ld1q)
sloejit_test(ld1r)
sloejit_test(ld1rb)
sloejit_test(ld1rd)
sloejit_test(ld1rh)
sloejit_test(ld1rqb)
sloejit_test(ld1rqd)
sloejit_test(ld1rqh)
sloejit_test(ld1rqw)
sloejit_test(ld1rw)
sloejit_test(ld1w)
sloejit_test(ld2)
sloejit_test(ld2b)
sloejit_test(ld2d)
sloejit_test(ld2h)
sloejit_test(ld2q)
sloejit_test(ld2w)
sloejit_test(ld3)
sloejit_test(ld3b)
sloejit_test(ld3d)
sloejit_test(ld3h)
sloejit_test(ld3q)
sloejit_test(ld3w)
sloejit_test(ld4)
sloejit_test(ld4b)
sloejit_test(ld4d)
sloejit_test(ld4h)
sloejit_test(ld4q)
sloejit_test(ld4w)
sloejit_test(ldp)
sloejit_test(ldr)
sloejit_test(ldrsb)
sloejit_test(lsl)
sloejit_test(lsr)
sloejit_test(madd)
sloejit_test(mova)
sloejit_test(movk)
sloejit_test(movn)
sloejit_test(movz)
sloejit_test(mul)
sloejit_test(orr)
sloejit_test(pfalse)
sloejit_test(ptrue)
sloejit_test(ret)
sloejit_test(rev)
sloejit_test(rev16)
sloejit_test(rev32)
sloejit_test(rev64)
sloejit_test(revb)
sloejit_test(revh)
sloejit_test(revw)
sloejit_test(sdiv)
sloejit_test(smlal)
sloejit_test(smlal2)
sloejit_test(smlalb)
sloejit_test(smlalt)
sloejit_test(smlsl)
sloejit_test(smlsl2)
sloejit_test(smlslb)
sloejit_test(smlslt)
sloejit_test(smov)
sloejit_test(smstart)
sloejit_test(smstop)
sloejit_test(smull)
sloejit_test(smull2)
sloejit_test(smullb)
sloejit_test(smullt)
sloejit_test(splice)
sloejit_test(sqadd)
sloejit_test(sqneg)
sloejit_test(sqrdcmlah)
sloejit_test(sqrdmlah)
sloejit_test(sqrdmlsh)
sloejit_test(sqrdmulh)
sloejit_test(sqrshrn)
sloejit_test(sqrshrn2)
sloejit_test(sqrshrnb)
sloejit_test(sqrshrnt)
sloejit_test(sqsub)
sloejit_test(srshr)
sloejit_test(st1)
sloejit_test(st1b)
sloejit_test(st1d)
sloejit_test(st1h)
sloejit_test(st1q)
sloejit_test(st1w)
sloejit_test(st2)
sloejit_test(st2b)
sloejit_test(st2d)
sloejit_test(st2h)
sloejit_test(st2q)
sloejit_test(st2w)
sloejit_test(st3)
sloejit_test(st3b)
sloejit_test(st3d)
sloejit_test(st3h)
sloejit_test(st3q)
sloejit_test(st3w)
sloejit_test(st4)
sloejit_test(st4b)
sloejit_test(st4d)
sloejit_test(st4h)
sloejit_test(st4q)
sloejit_test(st4w)
sloejit_test(stp)
sloejit_test(str)
sloejit_test(strb)
sloejit_test(sub)
sloejit_test(subs)
sloejit_test(trn1)
sloejit_test(trn2)
sloejit_test(udiv)
sloejit_test(uzp1)
sloejit_test(uzp2)
sloejit_test(whilele)
sloejit_test(whilelt)
sloejit_test(zip1)
sloejit_test(zip2)

add_test(
  NAME sloejit_verify_binary_test_cases
  COMMAND
    ${Python3_EXECUTABLE}
    ${CMAKE_CURRENT_SOURCE_DIR}/verify_binary_test_cases.py --compiler
    ${CMAKE_C_COMPILER} --compiler-id ${CMAKE_C_COMPILER_ID} --objdump
    ${CMAKE_OBJDUMP} ${SLOEJIT_TEST_FILES})
