/*
 * SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: MIT OR Apache-2.0 WITH LLVM-exception
 */

## Note: This file is not itself auto-generated.
## Only the files produced from this template are auto-generated.
/* ---------------------------------------------------------------------------
 *  AUTO-GENERATED FILE - DO NOT EDIT!
 *
 *  Generated by gen_asm_kernels.
 *  Any manual changes will be overwritten.
 * ---------------------------------------------------------------------------
 */

