# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0 WITH LLVM-exception

## Note: This file is not itself auto-generated.
## Only the files produced from this template are auto-generated.
# ---------------------------------------------------------------------------
#  AUTO-GENERATED FILE - DO NOT EDIT!
#
#  Generated by gen_asm_kernels.
#  Any manual changes will be overwritten.
# ---------------------------------------------------------------------------

enable_language(ASM)

include_directories("<%text>${</%text>CMAKE_CURRENT_LIST_DIR}/asm/include")

% for target in kernel_targets:
set(${target.name.upper()}_KERNEL_SOURCES
% for lookup in config:
% if target in lookup.targets:
  "<%text>${</%text>CMAKE_CURRENT_LIST_DIR}/asm/${target.name}/${lookup.src}"
% endif
% endfor
)
% endfor

target_sources(
  plfft_object PRIVATE
% for target in kernel_targets:
% if target.name != "sme":
  <%text>${</%text>${target.name.upper()}_KERNEL_SOURCES}
% endif
% endfor
)
% for target in kernel_targets:
% if target.name != "sme":
set_source_files_properties(
  <%text>${</%text>${target.name.upper()}_KERNEL_SOURCES}
  PROPERTIES COMPILE_OPTIONS "-march=${target.march}"
)
% endif
% endfor

if(ENABLE_SME)
  target_sources(plfft_object PRIVATE
% for target in kernel_targets:
% if target.name == "sme":
    <%text>${</%text>${target.name.upper()}_KERNEL_SOURCES}
% endif
% endfor
  )
% for target in kernel_targets:
% if target.name == "sme":
  set_source_files_properties(
    <%text>${</%text>${target.name.upper()}_KERNEL_SOURCES}
    PROPERTIES COMPILE_OPTIONS "-march=${target.march}"
  )
% endif
% endfor
endif()
