/*
 * SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: MIT OR Apache-2.0 WITH LLVM-exception
 */

/* ---------------------------------------------------------------------------
 *  AUTO-GENERATED FILE - DO NOT EDIT!
 *
 *  Generated by gen_asm_kernels.
 *  Any manual changes will be overwritten.
 * ---------------------------------------------------------------------------
 */

#pragma once

#include "kernel_data.hpp"
#include "plfft.h"
#include "plfft_complex.hpp"
#include "plfft_kernels.hpp"

namespace plfft {

template<typename Tx, typename Ty, order_kind order, dist_types dist,
         out_mods = out_mods::om_none, in_mods = in_mods::im_none>
fft_func_n_t<Tx, Ty> *lookup_fft_func_n(int64_t n, plfft_direction_t dir,
                                        bool want_sve, bool want_sme) {
  return nullptr;
}

template<typename Tw, order_kind order, dist_types dist,
         out_mods = out_mods::om_none, in_mods = in_mods::im_none>
fft_func_t_t<Tw> *lookup_fft_func_t(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme) {
  return nullptr;
}

template<typename Tw, order_kind order, dist_types dist,
         out_mods = out_mods::om_none, in_mods = in_mods::im_none>
fft_func_j_t<Tw> *lookup_fft_func_j(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme) {
  return nullptr;
}

template<typename Tw, order_kind order, dist_types dist,
         out_mods = out_mods::om_none, in_mods = in_mods::im_none>
fft_func_in_t<Tw> *lookup_fft_func_in(int64_t n, plfft_direction_t dir,
                                      bool want_sve, bool want_sme) {
  return nullptr;
}

template<typename Tw, order_kind order, dist_types dist,
         out_mods = out_mods::om_none, in_mods = in_mods::im_none>
fft_func_it_t<Tw> *lookup_fft_func_it(int64_t n, plfft_direction_t dir,
                                      bool want_sve, bool want_sme) {
  return nullptr;
}

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, std::complex<half>> *
lookup_fft_func_n<std::complex<half>, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::gs, out_mods::om_none, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, std::complex<half>> *
lookup_fft_func_n<std::complex<half>, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::gu, out_mods::om_none, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, std::complex<half>> *
lookup_fft_func_n<std::complex<half>, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::us, out_mods::om_none, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, std::complex<half>> *
lookup_fft_func_n<std::complex<half>, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::tu, out_mods::om_none, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, std::complex<half>> *
lookup_fft_func_n<std::complex<half>, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::om_none, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, std::complex<half>> *
lookup_fft_func_n<std::complex<half>, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::om_none, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_t_t<std::complex<half>> *
lookup_fft_func_t<std::complex<half>, order_kind::ORDER_AB, dist_types::gs,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_t_t<std::complex<half>> *
lookup_fft_func_t<std::complex<half>, order_kind::ORDER_AB, dist_types::gu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_t_t<std::complex<half>> *
lookup_fft_func_t<std::complex<half>, order_kind::ORDER_AB, dist_types::tu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_t_t<std::complex<half>> *
lookup_fft_func_t<std::complex<half>, order_kind::ORDER_AC, dist_types::tu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_t_t<std::complex<half>> *
lookup_fft_func_t<std::complex<half>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

template<>
fft_func_n_t<std::complex<float>, std::complex<float>> *
lookup_fft_func_n<std::complex<float>, std::complex<float>,
                  order_kind::ORDER_NA, dist_types::gs, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<float>, std::complex<float>> *
lookup_fft_func_n<std::complex<float>, std::complex<float>,
                  order_kind::ORDER_NA, dist_types::gu, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<float>, std::complex<float>> *
lookup_fft_func_n<std::complex<float>, std::complex<float>,
                  order_kind::ORDER_NA, dist_types::us, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<float>, std::complex<float>> *
lookup_fft_func_n<std::complex<float>, std::complex<float>,
                  order_kind::ORDER_NA, dist_types::tu, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<float>, std::complex<float>> *
lookup_fft_func_n<std::complex<float>, std::complex<float>,
                  order_kind::ORDER_NA, dist_types::uu, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<float>, std::complex<float>> *
lookup_fft_func_n<std::complex<float>, std::complex<float>,
                  order_kind::ORDER_NA, dist_types::uun, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_t_t<std::complex<float>> *
lookup_fft_func_t<std::complex<float>, order_kind::ORDER_AB, dist_types::gs,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);

template<>
fft_func_t_t<std::complex<float>> *
lookup_fft_func_t<std::complex<float>, order_kind::ORDER_AB, dist_types::gu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);

template<>
fft_func_t_t<std::complex<float>> *
lookup_fft_func_t<std::complex<float>, order_kind::ORDER_AB, dist_types::tu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);

template<>
fft_func_t_t<std::complex<float>> *
lookup_fft_func_t<std::complex<float>, order_kind::ORDER_AC, dist_types::tu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);

template<>
fft_func_t_t<std::complex<float>> *
lookup_fft_func_t<std::complex<float>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);

template<>
fft_func_n_t<std::complex<double>, std::complex<double>> *
lookup_fft_func_n<std::complex<double>, std::complex<double>,
                  order_kind::ORDER_NA, dist_types::gs, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<double>, std::complex<double>> *
lookup_fft_func_n<std::complex<double>, std::complex<double>,
                  order_kind::ORDER_NA, dist_types::gu, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<double>, std::complex<double>> *
lookup_fft_func_n<std::complex<double>, std::complex<double>,
                  order_kind::ORDER_NA, dist_types::us, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<double>, std::complex<double>> *
lookup_fft_func_n<std::complex<double>, std::complex<double>,
                  order_kind::ORDER_NA, dist_types::uu, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<double>, std::complex<double>> *
lookup_fft_func_n<std::complex<double>, std::complex<double>,
                  order_kind::ORDER_NA, dist_types::uun, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_t_t<std::complex<double>> *
lookup_fft_func_t<std::complex<double>, order_kind::ORDER_AB, dist_types::gs,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);

template<>
fft_func_t_t<std::complex<double>> *
lookup_fft_func_t<std::complex<double>, order_kind::ORDER_AB, dist_types::gu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);

template<>
fft_func_t_t<std::complex<double>> *
lookup_fft_func_t<std::complex<double>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, std::complex<int8_t>> *
lookup_fft_func_n<std::complex<int8_t>, std::complex<int8_t>,
                  order_kind::ORDER_NA, dist_types::gs, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, std::complex<int8_t>> *
lookup_fft_func_n<std::complex<int8_t>, std::complex<int8_t>,
                  order_kind::ORDER_NA, dist_types::gu, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, std::complex<int8_t>> *
lookup_fft_func_n<std::complex<int8_t>, std::complex<int8_t>,
                  order_kind::ORDER_NA, dist_types::us, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, std::complex<int8_t>> *
lookup_fft_func_n<std::complex<int8_t>, std::complex<int8_t>,
                  order_kind::ORDER_NA, dist_types::uu, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, std::complex<int8_t>> *
lookup_fft_func_n<std::complex<int8_t>, std::complex<int8_t>,
                  order_kind::ORDER_NA, dist_types::uun, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_t_t<std::complex<int8_t>> *
lookup_fft_func_t<std::complex<int8_t>, order_kind::ORDER_AB, dist_types::gs,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_t_t<std::complex<int8_t>> *
lookup_fft_func_t<std::complex<int8_t>, order_kind::ORDER_AB, dist_types::gu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_t_t<std::complex<int8_t>> *
lookup_fft_func_t<std::complex<int8_t>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, std::complex<int16_t>> *
lookup_fft_func_n<std::complex<int16_t>, std::complex<int16_t>,
                  order_kind::ORDER_NA, dist_types::gs, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, std::complex<int16_t>> *
lookup_fft_func_n<std::complex<int16_t>, std::complex<int16_t>,
                  order_kind::ORDER_NA, dist_types::gu, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, std::complex<int16_t>> *
lookup_fft_func_n<std::complex<int16_t>, std::complex<int16_t>,
                  order_kind::ORDER_NA, dist_types::us, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, std::complex<int16_t>> *
lookup_fft_func_n<std::complex<int16_t>, std::complex<int16_t>,
                  order_kind::ORDER_NA, dist_types::uu, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, std::complex<int16_t>> *
lookup_fft_func_n<std::complex<int16_t>, std::complex<int16_t>,
                  order_kind::ORDER_NA, dist_types::uun, out_mods::om_none,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_t_t<std::complex<int16_t>> *
lookup_fft_func_t<std::complex<int16_t>, order_kind::ORDER_AB, dist_types::gs,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_t_t<std::complex<int16_t>> *
lookup_fft_func_t<std::complex<int16_t>, order_kind::ORDER_AB, dist_types::gu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_t_t<std::complex<int16_t>> *
lookup_fft_func_t<std::complex<int16_t>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::om_none, in_mods::im_none>(int64_t n,
                                                       plfft_direction_t dir,
                                                       bool want_sve,
                                                       bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, half> *
lookup_fft_func_n<std::complex<half>, half, order_kind::ORDER_NA,
                  dist_types::gs, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, half> *
lookup_fft_func_n<std::complex<half>, half, order_kind::ORDER_NA,
                  dist_types::gu, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, half> *
lookup_fft_func_n<std::complex<half>, half, order_kind::ORDER_NA,
                  dist_types::us, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, half> *
lookup_fft_func_n<std::complex<half>, half, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, half> *
lookup_fft_func_n<std::complex<half>, half, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_in_t<std::complex<half>> *
lookup_fft_func_in<std::complex<half>, order_kind::ORDER_NA, dist_types::uu,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_in_t<std::complex<half>> *
lookup_fft_func_in<std::complex<half>, order_kind::ORDER_NA, dist_types::uun,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_it_t<std::complex<half>> *
lookup_fft_func_it<std::complex<half>, order_kind::ORDER_AB, dist_types::gs,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_it_t<std::complex<half>> *
lookup_fft_func_it<std::complex<half>, order_kind::ORDER_AB, dist_types::us,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_it_t<std::complex<half>> *
lookup_fft_func_it<std::complex<half>, order_kind::ORDER_AB, dist_types::gs,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_it_t<std::complex<half>> *
lookup_fft_func_it<std::complex<half>, order_kind::ORDER_AB, dist_types::us,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_it_t<std::complex<half>> *
lookup_fft_func_it<std::complex<half>, order_kind::ORDER_AC, dist_types::uu,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_it_t<std::complex<half>> *
lookup_fft_func_it<std::complex<half>, order_kind::ORDER_AC, dist_types::uu,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

template<>
fft_func_n_t<std::complex<float>, float> *
lookup_fft_func_n<std::complex<float>, float, order_kind::ORDER_NA,
                  dist_types::gs, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<float>, float> *
lookup_fft_func_n<std::complex<float>, float, order_kind::ORDER_NA,
                  dist_types::gu, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<float>, float> *
lookup_fft_func_n<std::complex<float>, float, order_kind::ORDER_NA,
                  dist_types::us, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<float>, float> *
lookup_fft_func_n<std::complex<float>, float, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<float>, float> *
lookup_fft_func_n<std::complex<float>, float, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_in_t<std::complex<float>> *
lookup_fft_func_in<std::complex<float>, order_kind::ORDER_NA, dist_types::uu,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_in_t<std::complex<float>> *
lookup_fft_func_in<std::complex<float>, order_kind::ORDER_NA, dist_types::uun,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<float>> *
lookup_fft_func_it<std::complex<float>, order_kind::ORDER_AB, dist_types::gs,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<float>> *
lookup_fft_func_it<std::complex<float>, order_kind::ORDER_AB, dist_types::us,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<float>> *
lookup_fft_func_it<std::complex<float>, order_kind::ORDER_AB, dist_types::gs,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<float>> *
lookup_fft_func_it<std::complex<float>, order_kind::ORDER_AB, dist_types::us,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<float>> *
lookup_fft_func_it<std::complex<float>, order_kind::ORDER_AC, dist_types::uu,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<float>> *
lookup_fft_func_it<std::complex<float>, order_kind::ORDER_AC, dist_types::uu,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_n_t<std::complex<double>, double> *
lookup_fft_func_n<std::complex<double>, double, order_kind::ORDER_NA,
                  dist_types::gs, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<double>, double> *
lookup_fft_func_n<std::complex<double>, double, order_kind::ORDER_NA,
                  dist_types::gu, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<double>, double> *
lookup_fft_func_n<std::complex<double>, double, order_kind::ORDER_NA,
                  dist_types::us, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<double>, double> *
lookup_fft_func_n<std::complex<double>, double, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<double>, double> *
lookup_fft_func_n<std::complex<double>, double, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_in_t<std::complex<double>> *
lookup_fft_func_in<std::complex<double>, order_kind::ORDER_NA, dist_types::uu,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_in_t<std::complex<double>> *
lookup_fft_func_in<std::complex<double>, order_kind::ORDER_NA, dist_types::uun,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<double>> *
lookup_fft_func_it<std::complex<double>, order_kind::ORDER_AB, dist_types::gs,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<double>> *
lookup_fft_func_it<std::complex<double>, order_kind::ORDER_AB, dist_types::us,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<double>> *
lookup_fft_func_it<std::complex<double>, order_kind::ORDER_AB, dist_types::gs,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<double>> *
lookup_fft_func_it<std::complex<double>, order_kind::ORDER_AB, dist_types::us,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<double>> *
lookup_fft_func_it<std::complex<double>, order_kind::ORDER_AC, dist_types::uu,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

template<>
fft_func_it_t<std::complex<double>> *
lookup_fft_func_it<std::complex<double>, order_kind::ORDER_AC, dist_types::uu,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, int8_t> *
lookup_fft_func_n<std::complex<int8_t>, int8_t, order_kind::ORDER_NA,
                  dist_types::gs, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, int8_t> *
lookup_fft_func_n<std::complex<int8_t>, int8_t, order_kind::ORDER_NA,
                  dist_types::gu, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, int8_t> *
lookup_fft_func_n<std::complex<int8_t>, int8_t, order_kind::ORDER_NA,
                  dist_types::us, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, int8_t> *
lookup_fft_func_n<std::complex<int8_t>, int8_t, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, int8_t> *
lookup_fft_func_n<std::complex<int8_t>, int8_t, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_in_t<std::complex<int8_t>> *
lookup_fft_func_in<std::complex<int8_t>, order_kind::ORDER_NA, dist_types::uu,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_in_t<std::complex<int8_t>> *
lookup_fft_func_in<std::complex<int8_t>, order_kind::ORDER_NA, dist_types::uun,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_it_t<std::complex<int8_t>> *
lookup_fft_func_it<std::complex<int8_t>, order_kind::ORDER_AB, dist_types::gs,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_it_t<std::complex<int8_t>> *
lookup_fft_func_it<std::complex<int8_t>, order_kind::ORDER_AB, dist_types::us,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_it_t<std::complex<int8_t>> *
lookup_fft_func_it<std::complex<int8_t>, order_kind::ORDER_AC, dist_types::uu,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, int16_t> *
lookup_fft_func_n<std::complex<int16_t>, int16_t, order_kind::ORDER_NA,
                  dist_types::gs, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, int16_t> *
lookup_fft_func_n<std::complex<int16_t>, int16_t, order_kind::ORDER_NA,
                  dist_types::gu, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, int16_t> *
lookup_fft_func_n<std::complex<int16_t>, int16_t, order_kind::ORDER_NA,
                  dist_types::us, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, int16_t> *
lookup_fft_func_n<std::complex<int16_t>, int16_t, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, int16_t> *
lookup_fft_func_n<std::complex<int16_t>, int16_t, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::om_real, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_in_t<std::complex<int16_t>> *
lookup_fft_func_in<std::complex<int16_t>, order_kind::ORDER_NA, dist_types::uu,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_in_t<std::complex<int16_t>> *
lookup_fft_func_in<std::complex<int16_t>, order_kind::ORDER_NA, dist_types::uun,
                   out_mods::om_none, in_mods::im_halfhi>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_it_t<std::complex<int16_t>> *
lookup_fft_func_it<std::complex<int16_t>, order_kind::ORDER_AB, dist_types::gs,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_it_t<std::complex<int16_t>> *
lookup_fft_func_it<std::complex<int16_t>, order_kind::ORDER_AB, dist_types::us,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_it_t<std::complex<int16_t>> *
lookup_fft_func_it<std::complex<int16_t>, order_kind::ORDER_AC, dist_types::uu,
                   out_mods::om_none, in_mods::im_halflo>(int64_t n,
                                                          plfft_direction_t dir,
                                                          bool want_sve,
                                                          bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<half, std::complex<half>> *
lookup_fft_func_n<half, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::gs, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<half, std::complex<half>> *
lookup_fft_func_n<half, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::gu, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<half, std::complex<half>> *
lookup_fft_func_n<half, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::us, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<half, std::complex<half>> *
lookup_fft_func_n<half, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<half, std::complex<half>> *
lookup_fft_func_n<half, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, std::complex<half>> *
lookup_fft_func_n<std::complex<half>, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::halfhi, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_n_t<std::complex<half>, std::complex<half>> *
lookup_fft_func_n<std::complex<half>, std::complex<half>, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::halfhi, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_j_t<std::complex<half>> *
lookup_fft_func_j<std::complex<half>, order_kind::ORDER_AB, dist_types::gs,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_j_t<std::complex<half>> *
lookup_fft_func_j<std::complex<half>, order_kind::ORDER_AB, dist_types::gu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_j_t<std::complex<half>> *
lookup_fft_func_j<std::complex<half>, order_kind::ORDER_AB, dist_types::tu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_t_t<std::complex<half>> *
lookup_fft_func_t<std::complex<half>, order_kind::ORDER_AB, dist_types::uun,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_t_t<std::complex<half>> *
lookup_fft_func_t<std::complex<half>, order_kind::ORDER_AB, dist_types::uu,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_j_t<std::complex<half>> *
lookup_fft_func_j<std::complex<half>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
template<>
fft_func_t_t<std::complex<half>> *
lookup_fft_func_t<std::complex<half>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

template<>
fft_func_n_t<float, std::complex<float>> *
lookup_fft_func_n<float, std::complex<float>, order_kind::ORDER_NA,
                  dist_types::gs, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<float, std::complex<float>> *
lookup_fft_func_n<float, std::complex<float>, order_kind::ORDER_NA,
                  dist_types::gu, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<float, std::complex<float>> *
lookup_fft_func_n<float, std::complex<float>, order_kind::ORDER_NA,
                  dist_types::us, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<float, std::complex<float>> *
lookup_fft_func_n<float, std::complex<float>, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<float, std::complex<float>> *
lookup_fft_func_n<float, std::complex<float>, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<float>, std::complex<float>> *
lookup_fft_func_n<std::complex<float>, std::complex<float>,
                  order_kind::ORDER_NA, dist_types::uu, out_mods::halfhi,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<float>, std::complex<float>> *
lookup_fft_func_n<std::complex<float>, std::complex<float>,
                  order_kind::ORDER_NA, dist_types::uun, out_mods::halfhi,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_j_t<std::complex<float>> *
lookup_fft_func_j<std::complex<float>, order_kind::ORDER_AB, dist_types::gs,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_j_t<std::complex<float>> *
lookup_fft_func_j<std::complex<float>, order_kind::ORDER_AB, dist_types::gu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_j_t<std::complex<float>> *
lookup_fft_func_j<std::complex<float>, order_kind::ORDER_AB, dist_types::tu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_t_t<std::complex<float>> *
lookup_fft_func_t<std::complex<float>, order_kind::ORDER_AB, dist_types::uun,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);

template<>
fft_func_t_t<std::complex<float>> *
lookup_fft_func_t<std::complex<float>, order_kind::ORDER_AB, dist_types::uu,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);

template<>
fft_func_j_t<std::complex<float>> *
lookup_fft_func_j<std::complex<float>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_t_t<std::complex<float>> *
lookup_fft_func_t<std::complex<float>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);

template<>
fft_func_n_t<double, std::complex<double>> *
lookup_fft_func_n<double, std::complex<double>, order_kind::ORDER_NA,
                  dist_types::gs, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<double, std::complex<double>> *
lookup_fft_func_n<double, std::complex<double>, order_kind::ORDER_NA,
                  dist_types::gu, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<double, std::complex<double>> *
lookup_fft_func_n<double, std::complex<double>, order_kind::ORDER_NA,
                  dist_types::us, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<double, std::complex<double>> *
lookup_fft_func_n<double, std::complex<double>, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<double, std::complex<double>> *
lookup_fft_func_n<double, std::complex<double>, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<double>, std::complex<double>> *
lookup_fft_func_n<std::complex<double>, std::complex<double>,
                  order_kind::ORDER_NA, dist_types::uu, out_mods::halfhi,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_n_t<std::complex<double>, std::complex<double>> *
lookup_fft_func_n<std::complex<double>, std::complex<double>,
                  order_kind::ORDER_NA, dist_types::uun, out_mods::halfhi,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);

template<>
fft_func_j_t<std::complex<double>> *
lookup_fft_func_j<std::complex<double>, order_kind::ORDER_AB, dist_types::gs,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_j_t<std::complex<double>> *
lookup_fft_func_j<std::complex<double>, order_kind::ORDER_AB, dist_types::gu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_t_t<std::complex<double>> *
lookup_fft_func_t<std::complex<double>, order_kind::ORDER_AB, dist_types::uun,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);

template<>
fft_func_t_t<std::complex<double>> *
lookup_fft_func_t<std::complex<double>, order_kind::ORDER_AB, dist_types::uu,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);

template<>
fft_func_j_t<std::complex<double>> *
lookup_fft_func_j<std::complex<double>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);

template<>
fft_func_t_t<std::complex<double>> *
lookup_fft_func_t<std::complex<double>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<int8_t, std::complex<int8_t>> *
lookup_fft_func_n<int8_t, std::complex<int8_t>, order_kind::ORDER_NA,
                  dist_types::gs, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<int8_t, std::complex<int8_t>> *
lookup_fft_func_n<int8_t, std::complex<int8_t>, order_kind::ORDER_NA,
                  dist_types::gu, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<int8_t, std::complex<int8_t>> *
lookup_fft_func_n<int8_t, std::complex<int8_t>, order_kind::ORDER_NA,
                  dist_types::us, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<int8_t, std::complex<int8_t>> *
lookup_fft_func_n<int8_t, std::complex<int8_t>, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<int8_t, std::complex<int8_t>> *
lookup_fft_func_n<int8_t, std::complex<int8_t>, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, std::complex<int8_t>> *
lookup_fft_func_n<std::complex<int8_t>, std::complex<int8_t>,
                  order_kind::ORDER_NA, dist_types::uu, out_mods::halfhi,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int8_t>, std::complex<int8_t>> *
lookup_fft_func_n<std::complex<int8_t>, std::complex<int8_t>,
                  order_kind::ORDER_NA, dist_types::uun, out_mods::halfhi,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_j_t<std::complex<int8_t>> *
lookup_fft_func_j<std::complex<int8_t>, order_kind::ORDER_AB, dist_types::gs,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_j_t<std::complex<int8_t>> *
lookup_fft_func_j<std::complex<int8_t>, order_kind::ORDER_AB, dist_types::gu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_t_t<std::complex<int8_t>> *
lookup_fft_func_t<std::complex<int8_t>, order_kind::ORDER_AB, dist_types::uun,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_j_t<std::complex<int8_t>> *
lookup_fft_func_j<std::complex<int8_t>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_t_t<std::complex<int8_t>> *
lookup_fft_func_t<std::complex<int8_t>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<int16_t, std::complex<int16_t>> *
lookup_fft_func_n<int16_t, std::complex<int16_t>, order_kind::ORDER_NA,
                  dist_types::gs, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<int16_t, std::complex<int16_t>> *
lookup_fft_func_n<int16_t, std::complex<int16_t>, order_kind::ORDER_NA,
                  dist_types::gu, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<int16_t, std::complex<int16_t>> *
lookup_fft_func_n<int16_t, std::complex<int16_t>, order_kind::ORDER_NA,
                  dist_types::us, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<int16_t, std::complex<int16_t>> *
lookup_fft_func_n<int16_t, std::complex<int16_t>, order_kind::ORDER_NA,
                  dist_types::uu, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<int16_t, std::complex<int16_t>> *
lookup_fft_func_n<int16_t, std::complex<int16_t>, order_kind::ORDER_NA,
                  dist_types::uun, out_mods::halfhi, in_mods::im_real>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, std::complex<int16_t>> *
lookup_fft_func_n<std::complex<int16_t>, std::complex<int16_t>,
                  order_kind::ORDER_NA, dist_types::uu, out_mods::halfhi,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_n_t<std::complex<int16_t>, std::complex<int16_t>> *
lookup_fft_func_n<std::complex<int16_t>, std::complex<int16_t>,
                  order_kind::ORDER_NA, dist_types::uun, out_mods::halfhi,
                  in_mods::im_none>(int64_t n, plfft_direction_t dir,
                                    bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_j_t<std::complex<int16_t>> *
lookup_fft_func_j<std::complex<int16_t>, order_kind::ORDER_AB, dist_types::gs,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_j_t<std::complex<int16_t>> *
lookup_fft_func_j<std::complex<int16_t>, order_kind::ORDER_AB, dist_types::gu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_t_t<std::complex<int16_t>> *
lookup_fft_func_t<std::complex<int16_t>, order_kind::ORDER_AB, dist_types::uun,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_j_t<std::complex<int16_t>> *
lookup_fft_func_j<std::complex<int16_t>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::conj_reverse, in_mods::im_none>(
    int64_t n, plfft_direction_t dir, bool want_sve, bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

#if PLFFT_ENABLE_FIXED_POINT
template<>
fft_func_t_t<std::complex<int16_t>> *
lookup_fft_func_t<std::complex<int16_t>, order_kind::ORDER_AC, dist_types::uu,
                  out_mods::halflo, in_mods::im_none>(int64_t n,
                                                      plfft_direction_t dir,
                                                      bool want_sve,
                                                      bool want_sme);
#endif // PLFFT_ENABLE_FIXED_POINT

} // namespace plfft
